<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Actions', description: 'Gestion des actions, permission ACTION_GERER requise.')]
#[OA\Tag(name: 'Menus', description: 'Gestion des menus, permission MENU_GERER requise.')]
#[OA\Get(path: '/administration/actions', tags: ['Actions'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Liste des actions'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Post(path: '/administration/actions', tags: ['Actions'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Action créée'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Get(path: '/administration/actions/{action}', tags: ['Actions'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'action', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Détail de l’action'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 404, description: 'Action introuvable')])]
#[OA\Put(path: '/administration/actions/{action}', tags: ['Actions'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'action', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Action modifiée'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Patch(path: '/administration/actions/{action}', tags: ['Actions'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'action', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Action modifiée'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Delete(path: '/administration/actions/{action}', tags: ['Actions'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'action', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Action supprimée'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 404, description: 'Action introuvable')])]
#[OA\Get(path: '/administration/menus', tags: ['Menus'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Liste des menus'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Post(path: '/administration/menus', tags: ['Menus'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Menu créé'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Get(path: '/administration/menus/{menu}', tags: ['Menus'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'menu', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Détail du menu'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 404, description: 'Menu introuvable')])]
#[OA\Put(path: '/administration/menus/{menu}', tags: ['Menus'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'menu', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Menu modifié'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Patch(path: '/administration/menus/{menu}', tags: ['Menus'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'menu', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Menu modifié'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Delete(path: '/administration/menus/{menu}', tags: ['Menus'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'menu', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Menu supprimé'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 404, description: 'Menu introuvable')])]
final class ActionMenuDocumentation
{
}
