<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'AffectationEnseignantPayload', type: 'object', required: ['id_annee_academique', 'enseignant_id', 'portee', 'id_matiere', 'date_debut'], properties: [
    new OA\Property(property: 'id_annee_academique', type: 'integer', minimum: 1, example: 1), new OA\Property(property: 'enseignant_id', type: 'integer', minimum: 1, example: 12),
    new OA\Property(property: 'portee', type: 'string', enum: ['matiere', 'cours'], example: 'matiere'), new OA\Property(property: 'id_matiere', type: 'integer', minimum: 1, example: 4),
    new OA\Property(property: 'id_cours', description: 'Obligatoire lorsque portee vaut cours, interdit pour matiere.', type: 'integer', nullable: true, minimum: 1, example: 15),
    new OA\Property(property: 'date_debut', type: 'string', format: 'date', example: '2026-09-12'),
])]
#[OA\Schema(schema: 'AffectationEnseignant', type: 'object', properties: [
    new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'id_annee_academique', type: 'integer'), new OA\Property(property: 'enseignant_id', type: 'integer'),
    new OA\Property(property: 'id_matiere', type: 'integer'), new OA\Property(property: 'id_cours', type: 'integer', nullable: true), new OA\Property(property: 'portee', type: 'string', enum: ['matiere', 'cours']),
    new OA\Property(property: 'date_debut', type: 'string', format: 'date'), new OA\Property(property: 'date_fin', type: 'string', format: 'date', nullable: true), new OA\Property(property: 'motif_fin', type: 'string', nullable: true),
    new OA\Property(property: 'statut', type: 'string', enum: ['en_cours', 'terminee']), new OA\Property(property: 'volume_horaire', type: 'number', nullable: true),
    new OA\Property(property: 'enseignant', type: 'object'), new OA\Property(property: 'matiere', type: 'object'), new OA\Property(property: 'cours', type: 'object', nullable: true), new OA\Property(property: 'annee_academique', type: 'object'),
])]
#[OA\Get(path: '/administration/affectations-enseignants/tableau-de-bord', operationId: 'tableauDeBordAffectationsEnseignants', summary: 'Obtenir les indicateurs des affectations', tags: ['Affectations enseignants'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id_annee_academique', in: 'query', required: true, schema: new OA\Schema(type: 'integer', minimum: 1))], responses: [new OA\Response(response: 200, description: 'Indicateurs.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'indicateurs', type: 'object', properties: [new OA\Property(property: 'enseignements_confies', type: 'integer'), new OA\Property(property: 'enseignants_mobilises', type: 'integer'), new OA\Property(property: 'cours_sans_enseignant', type: 'integer'), new OA\Property(property: 'enseignants_sans_charge', type: 'integer')])])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 422, description: 'Année invalide')])]
#[OA\Get(path: '/administration/affectations-enseignants/options', operationId: 'optionsAffectationsEnseignants', summary: 'Charger enseignants, matières et cours éligibles', tags: ['Affectations enseignants'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id_annee_academique', in: 'query', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'id_matiere', in: 'query', required: false, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Options.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'enseignants', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'enseignants_exclus', type: 'integer'), new OA\Property(property: 'matieres', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'cours', type: 'array', items: new OA\Items(type: 'object'))])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 422, description: 'Paramètres invalides')])]
#[OA\Get(path: '/administration/affectations-enseignants', operationId: 'listerAffectationsEnseignants', summary: 'Lister les affectations et leur historique', tags: ['Affectations enseignants'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id_annee_academique', in: 'query', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'statut', in: 'query', schema: new OA\Schema(type: 'string', enum: ['en_cours', 'terminee'])), new OA\Parameter(name: 'recherche', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', maximum: 100))], responses: [new OA\Response(response: 200, description: 'Liste paginée.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'affectations', type: 'array', items: new OA\Items(ref: '#/components/schemas/AffectationEnseignant')), new OA\Property(property: 'meta', type: 'object')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 422, description: 'Filtres invalides')])]
#[OA\Post(path: '/administration/affectations-enseignants', operationId: 'creerAffectationEnseignant', summary: 'Confier un enseignement', description: 'Une affectation matière couvre tous ses cours actuels et futurs. Les chevauchements de couverture sont refusés.', tags: ['Affectations enseignants'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/AffectationEnseignantPayload')), responses: [new OA\Response(response: 201, description: 'Affectation créée.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string'), new OA\Property(property: 'affectation', ref: '#/components/schemas/AffectationEnseignant')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 422, description: 'Données ou couverture invalides', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Get(path: '/administration/affectations-enseignants/{id}', operationId: 'afficherAffectationEnseignant', summary: 'Afficher une affectation', tags: ['Affectations enseignants'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Affectation trouvée.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'affectation', ref: '#/components/schemas/AffectationEnseignant')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 404, description: 'Affectation introuvable')])]
#[OA\Patch(path: '/administration/affectations-enseignants/{id}/terminer', operationId: 'terminerAffectationEnseignant', summary: 'Terminer une affectation sans supprimer son historique', description: 'Une date antérieure à une note déjà saisie dans la matière est refusée.', tags: ['Affectations enseignants'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object', required: ['date_fin'], properties: [new OA\Property(property: 'date_fin', type: 'string', format: 'date', example: '2026-09-12'), new OA\Property(property: 'motif', type: 'string', nullable: true, maxLength: 2000)])), responses: [new OA\Response(response: 200, description: 'Affectation terminée.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string'), new OA\Property(property: 'affectation', ref: '#/components/schemas/AffectationEnseignant')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 404, description: 'Affectation introuvable'), new OA\Response(response: 422, description: 'Date invalide', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
final class AffectationEnseignantDocumentation {}
