<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Authentification', description: 'Connexion, double authentification, profil de session et gestion du mot de passe.')]
#[OA\Post(path: '/auth/connexion', tags: ['Authentification'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email', 'password'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'password', type: 'string', format: 'password'), new OA\Property(property: 'nom_appareil', type: 'string')])), responses: [new OA\Response(response: 200, description: 'Connexion directe réussie'), new OA\Response(response: 202, description: 'Code OTP envoyé'), new OA\Response(response: 403, description: 'Compte inactif'), new OA\Response(response: 422, description: 'Identifiants invalides'), new OA\Response(response: 429, description: 'Trop de tentatives')])]
#[OA\Post(path: '/auth/confirmer-otp', tags: ['Authentification'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['id_tentative', 'code_otp'], properties: [new OA\Property(property: 'id_tentative', type: 'integer'), new OA\Property(property: 'code_otp', type: 'string', example: '123456')])), responses: [new OA\Response(response: 200, description: 'OTP validé et jeton retourné'), new OA\Response(response: 403, description: 'Compte inactif'), new OA\Response(response: 422, description: 'OTP invalide ou expiré'), new OA\Response(response: 429, description: 'Trop de tentatives')])]
#[OA\Post(path: '/auth/mot-de-passe-oublie', tags: ['Authentification'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email')])), responses: [new OA\Response(response: 200, description: 'Demande prise en compte'), new OA\Response(response: 422, description: 'Données invalides'), new OA\Response(response: 429, description: 'Trop de tentatives'), new OA\Response(response: 503, description: 'Envoi du courriel impossible')])]
#[OA\Post(path: '/auth/verifier-code-reinitialisation', tags: ['Authentification'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email', 'code_otp'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'code_otp', type: 'string', example: '123456')])), responses: [new OA\Response(response: 200, description: 'Code vérifié et jeton de réinitialisation retourné'), new OA\Response(response: 422, description: 'Code invalide ou expiré'), new OA\Response(response: 429, description: 'Trop de tentatives')])]
#[OA\Post(path: '/auth/reinitialiser-mot-de-passe', tags: ['Authentification'], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email', 'reset_token', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'reset_token', type: 'string'), new OA\Property(property: 'password', type: 'string', format: 'password'), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password')])), responses: [new OA\Response(response: 200, description: 'Mot de passe réinitialisé'), new OA\Response(response: 422, description: 'Données ou jeton invalides'), new OA\Response(response: 429, description: 'Trop de tentatives')])]
#[OA\Post(path: '/auth/modifier-mot-de-passe', tags: ['Authentification'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['mot_de_passe_actuel', 'password', 'password_confirmation'], properties: [new OA\Property(property: 'mot_de_passe_actuel', type: 'string', format: 'password'), new OA\Property(property: 'password', type: 'string', format: 'password'), new OA\Property(property: 'password_confirmation', type: 'string', format: 'password')])), responses: [new OA\Response(response: 200, description: 'Mot de passe modifié'), new OA\Response(response: 401, description: 'Non authentifié'), new OA\Response(response: 422, description: 'Données invalides'), new OA\Response(response: 429, description: 'Trop de tentatives')])]
#[OA\Get(path: '/auth/profil', tags: ['Authentification'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Profil de l’utilisateur connecté'), new OA\Response(response: 401, description: 'Non authentifié'), new OA\Response(response: 403, description: 'Compte inactif')])]
#[OA\Post(path: '/auth/deconnexion', tags: ['Authentification'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Session courante déconnectée'), new OA\Response(response: 401, description: 'Non authentifié')])]
#[OA\Post(path: '/auth/deconnexion-globale', tags: ['Authentification'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Toutes les sessions sont déconnectées'), new OA\Response(response: 401, description: 'Non authentifié')])]
final class AuthentificationDocumentation
{
}
