<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(
    name: 'Comptes',
    description: 'Création accessible avec COMPTE_GERER ou au rôle SECRETAIRE_ACADEMIQUE. Les rôles ETUDIANT et ENSEIGNANT sont interdits. Les autres opérations exigent COMPTE_GERER.',
)]
#[OA\Get(path: '/administration/comptes', tags: ['Comptes'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Liste des comptes'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit')])]
#[OA\Post(path: '/administration/comptes', tags: ['Comptes'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Compte créé'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Get(path: '/administration/comptes/create', tags: ['Comptes'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Données nécessaires au formulaire de création'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit')])]
#[OA\Post(path: '/administration/comptes/etudiants', tags: ['Comptes'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Compte étudiant créé'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Get(path: '/administration/comptes/{compte}', tags: ['Comptes'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'compte', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Détail du compte'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 404, description: 'Compte introuvable')])]
#[OA\Put(path: '/administration/comptes/{compte}', tags: ['Comptes'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'compte', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Compte modifié'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Patch(path: '/administration/comptes/{compte}', tags: ['Comptes'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'compte', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Compte modifié'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Post(path: '/administration/comptes/{compte}', tags: ['Comptes'], description: 'Modification multipart/form-data.', security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'compte', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(type: 'object'))), responses: [new OA\Response(response: 200, description: 'Compte modifié'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Delete(path: '/administration/comptes/{compte}', tags: ['Comptes'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'compte', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Compte supprimé'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 404, description: 'Compte introuvable')])]
#[OA\Get(path: '/administration/comptes/{compte}/edit', tags: ['Comptes'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'compte', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Données nécessaires au formulaire de modification'), new OA\Response(response: 403, description: 'Permission absente ou rôle ETUDIANT/ENSEIGNANT interdit'), new OA\Response(response: 404, description: 'Compte introuvable')])]
final class CompteDocumentation
{
}
