<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'CreneauPayload', description: 'Creneau hebdomadaire dans un module du calendrier. Cours et promotion facultatifs. Conflits de salle, enseignant ou niveau refus?s avec 422. Les horaires adjacents sont autoris?s.', type: 'object', required: ['id_module_calendrier', 'id_niveau', 'id_matiere', 'enseignant_id', 'id_salle', 'jour', 'heure_debut', 'heure_fin'], properties: [new OA\Property(property: 'id_module_calendrier', type: 'integer', example: 1), new OA\Property(property: 'id_niveau', type: 'integer', example: 1), new OA\Property(property: 'id_matiere', type: 'integer', example: 1), new OA\Property(property: 'id_cours', type: 'integer', nullable: true), new OA\Property(property: 'id_promotion', type: 'integer', nullable: true), new OA\Property(property: 'enseignant_id', type: 'integer', example: 2), new OA\Property(property: 'id_salle', type: 'integer', example: 1), new OA\Property(property: 'jour', type: 'integer', example: 1, description: '1 = lundi, 7 = dimanche', minimum: 1, maximum: 7), new OA\Property(property: 'heure_debut', type: 'string', example: '08:00', pattern: '^[0-2][0-9]:[0-5][0-9]$'), new OA\Property(property: 'heure_fin', type: 'string', example: '10:00', pattern: '^[0-2][0-9]:[0-5][0-9]$')])]
#[OA\Schema(schema: 'CreneauModification', description: 'Cr?neau hebdomadaire dans un module du calendrier. Cours et promotion facultatifs. Conflits de salle, enseignant ou niveau refusés avec 422. Les horaires adjacents sont autorisés.', type: 'object', properties: [new OA\Property(property: 'id_module_calendrier', type: 'integer', example: 1), new OA\Property(property: 'id_niveau', type: 'integer', example: 1), new OA\Property(property: 'id_matiere', type: 'integer', example: 1), new OA\Property(property: 'id_cours', type: 'integer', nullable: true), new OA\Property(property: 'id_promotion', type: 'integer', nullable: true), new OA\Property(property: 'enseignant_id', type: 'integer', example: 2), new OA\Property(property: 'id_salle', type: 'integer', example: 1), new OA\Property(property: 'jour', type: 'integer', example: 1, description: '1 = lundi, 7 = dimanche', minimum: 1, maximum: 7), new OA\Property(property: 'heure_debut', type: 'string', example: '08:00', pattern: '^[0-2][0-9]:[0-5][0-9]$'), new OA\Property(property: 'heure_fin', type: 'string', example: '10:00', pattern: '^[0-2][0-9]:[0-5][0-9]$')])]
#[OA\Schema(schema: 'Creneau', type: 'object', allOf: [new OA\Schema(ref: '#/components/schemas/CreneauPayload')], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'id_annee_academique', type: 'integer'), new OA\Property(property: 'duree_minutes', type: 'integer'), new OA\Property(property: 'module_calendrier', type: 'object', nullable: true), new OA\Property(property: 'niveau', type: 'object', nullable: true), new OA\Property(property: 'matiere', type: 'object', nullable: true), new OA\Property(property: 'cours', type: 'object', nullable: true), new OA\Property(property: 'promotion', type: 'object', nullable: true), new OA\Property(property: 'enseignant', type: 'object', nullable: true), new OA\Property(property: 'salle', type: 'object', nullable: true)])]
#[OA\Get(path: '/parametres/creneaux', operationId: 'listerCreneaux', summary: 'Lister le planning hebdomadaire', tags: ['Cr?neaux'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id_annee_academique', in: 'query', required: true, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'id_niveau', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'id_module_calendrier', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'id_promotion', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1))],
    responses: [new OA\Response(response: 200, description: 'Succ?s', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'creneaux', type: 'array', items: new OA\Items(ref: '#/components/schemas/Creneau')), new OA\Property(property: 'nombre_creneaux', type: 'integer'), new OA\Property(property: 'heures_hebdomadaires', type: 'number')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Acc?s r?serv? aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Get(path: '/parametres/creneaux/options', operationId: 'optionsCreneaux', summary: 'Charger les listes du formulaire', tags: ['Cr?neaux'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id_annee_academique', in: 'query', required: true, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'id_niveau', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'id_matiere', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1))],
    responses: [new OA\Response(response: 200, description: 'Succ?s', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'modules_calendrier', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'niveaux', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'promotions', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'matieres', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'cours', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'enseignants', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'salles', type: 'array', items: new OA\Items(type: 'object'))])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Acc?s r?serv? aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Post(path: '/parametres/creneaux', operationId: 'creerCreneau', summary: 'Cr?er un cr?neau', tags: ['Créneaux'], security: [['sanctum' => []]], parameters: [],
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreneauPayload')),
    responses: [new OA\Response(response: 201, description: 'Succès', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'creneau', ref: '#/components/schemas/Creneau')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Accès réservé aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Get(path: '/parametres/creneaux/{id}', operationId: 'afficherCreneau', summary: 'Afficher un cr?neau', tags: ['Cr?neaux'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))],
    responses: [new OA\Response(response: 200, description: 'Succès', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'creneau', ref: '#/components/schemas/Creneau')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Accès r?servé aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Put(path: '/parametres/creneaux/{id}', operationId: 'remplacerCreneau', summary: 'Modifier un créneau complet', tags: ['Cr?neaux'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))],
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreneauPayload')),
    responses: [new OA\Response(response: 200, description: 'Succès', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'creneau', ref: '#/components/schemas/Creneau')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Accès réservé aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Patch(path: '/parametres/creneaux/{id}', operationId: 'modifierCreneau', summary: 'Modifier partiellement un cr?neau', tags: ['Cr?neaux'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))],
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/CreneauModification')),
    responses: [new OA\Response(response: 200, description: 'Succès', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'creneau', ref: '#/components/schemas/Creneau')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Acc?s r?serv? aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Delete(path: '/parametres/creneaux/{id}', operationId: 'supprimerCreneau', summary: 'Supprimer logiquement un cr?neau', tags: ['Cr?neaux'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))],
    responses: [new OA\Response(response: 200, description: 'Succès', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Acc?s r?serv? aux comptes actifs ADMIN, SECRETAIRE_ACADEMIQUE et DIRECTION'), new OA\Response(response: 404, description: 'Ressource introuvable'), new OA\Response(response: 422, description: 'Validation ou conflit horaire', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
final class CreneauDocumentation {}
