<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'EvenementCalendrierPayload', type: 'object', required: ['id_calendrier', 'type', 'date_debut', 'date_fin'], properties: [
    new OA\Property(property: 'id_calendrier', type: 'integer', minimum: 1, example: 1),
    new OA\Property(property: 'id_module_calendrier', description: 'Obligatoire pour examen et rattrapage ; interdit pour les autres types.', type: 'integer', nullable: true, minimum: 1, example: 1),
    new OA\Property(property: 'type', type: 'string', enum: ['examen', 'rattrapage', 'jour_ferie', 'conge', 'grandes_vacances'], example: 'examen'),
    new OA\Property(property: 'libelle', description: 'Obligatoire pour jour_ferie et conge.', type: 'string', nullable: true, maxLength: 180, example: 'Examen final'),
    new OA\Property(property: 'date_debut', type: 'string', format: 'date', example: '2026-12-15'),
    new OA\Property(property: 'date_fin', type: 'string', format: 'date', example: '2026-12-20'),
])]
#[OA\Schema(schema: 'EvenementCalendrierModification', description: 'Tous les champs sont facultatifs avec PATCH.', type: 'object', properties: [
    new OA\Property(property: 'id_calendrier', type: 'integer', minimum: 1), new OA\Property(property: 'id_module_calendrier', type: 'integer', nullable: true, minimum: 1),
    new OA\Property(property: 'type', type: 'string', enum: ['examen', 'rattrapage', 'jour_ferie', 'conge', 'grandes_vacances']), new OA\Property(property: 'libelle', type: 'string', nullable: true, maxLength: 180),
    new OA\Property(property: 'date_debut', type: 'string', format: 'date'), new OA\Property(property: 'date_fin', type: 'string', format: 'date'),
])]
#[OA\Schema(schema: 'EvenementCalendrier', type: 'object', properties: [
    new OA\Property(property: 'id', type: 'integer', readOnly: true), new OA\Property(property: 'id_calendrier', type: 'integer'), new OA\Property(property: 'id_module_calendrier', type: 'integer', nullable: true),
    new OA\Property(property: 'type', type: 'string'), new OA\Property(property: 'libelle', type: 'string', nullable: true), new OA\Property(property: 'date_debut', type: 'string', format: 'date'), new OA\Property(property: 'date_fin', type: 'string', format: 'date'),
    new OA\Property(property: 'calendrier', type: 'object', nullable: true, readOnly: true), new OA\Property(property: 'module', type: 'object', nullable: true, readOnly: true),
    new OA\Property(property: 'created_at', type: 'string', format: 'date-time', readOnly: true), new OA\Property(property: 'updated_at', type: 'string', format: 'date-time', readOnly: true),
])]
#[OA\Get(path: '/parametres/evenements-calendrier', operationId: 'listerEvenementsCalendrier', summary: 'Lister les événements du calendrier', tags: ['Événements calendrier'], security: [['sanctum' => []]], parameters: [
    new OA\Parameter(name: 'id_calendrier', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'id_module_calendrier', in: 'query', required: false, schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'type', in: 'query', required: false, schema: new OA\Schema(type: 'string', enum: ['examen', 'rattrapage', 'jour_ferie', 'conge', 'grandes_vacances'])),
], responses: [new OA\Response(response: 200, description: 'Liste triée par date.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'evenements', type: 'array', items: new OA\Items(ref: '#/components/schemas/EvenementCalendrier'))])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 422, description: 'Filtre invalide', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Post(path: '/parametres/evenements-calendrier', operationId: 'creerEvenementCalendrier', summary: 'Créer un événement de calendrier', description: 'Un examen reste dans son module ; un rattrapage commence après son module ; une seule période de grandes vacances est autorisée.', tags: ['Événements calendrier'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/EvenementCalendrierPayload')), responses: [new OA\Response(response: 201, description: 'Événement créé.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string'), new OA\Property(property: 'evenement', ref: '#/components/schemas/EvenementCalendrier')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 422, description: 'Données invalides', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Get(path: '/parametres/evenements-calendrier/{id}', operationId: 'afficherEvenementCalendrier', summary: 'Afficher un événement de calendrier', tags: ['Événements calendrier'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer', minimum: 1))], responses: [new OA\Response(response: 200, description: 'Événement trouvé.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'evenement', ref: '#/components/schemas/EvenementCalendrier')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 404, description: 'Événement introuvable')])]
#[OA\Put(path: '/parametres/evenements-calendrier/{id}', operationId: 'remplacerEvenementCalendrier', summary: 'Remplacer complètement un événement', tags: ['Événements calendrier'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer', minimum: 1))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/EvenementCalendrierPayload')), responses: [new OA\Response(response: 200, description: 'Événement modifié.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string'), new OA\Property(property: 'evenement', ref: '#/components/schemas/EvenementCalendrier')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 404, description: 'Événement introuvable'), new OA\Response(response: 422, description: 'Données invalides', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Patch(path: '/parametres/evenements-calendrier/{id}', operationId: 'modifierEvenementCalendrier', summary: 'Modifier partiellement un événement', tags: ['Événements calendrier'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer', minimum: 1))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/EvenementCalendrierModification')), responses: [new OA\Response(response: 200, description: 'Événement modifié.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string'), new OA\Property(property: 'evenement', ref: '#/components/schemas/EvenementCalendrier')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 404, description: 'Événement introuvable'), new OA\Response(response: 422, description: 'Données invalides', content: new OA\JsonContent(ref: '#/components/schemas/ErreurValidation'))])]
#[OA\Delete(path: '/parametres/evenements-calendrier/{id}', operationId: 'supprimerEvenementCalendrier', summary: 'Supprimer un événement', tags: ['Événements calendrier'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer', minimum: 1))], responses: [new OA\Response(response: 200, description: 'Événement supprimé.', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'message', type: 'string', example: 'Événement supprimé avec succès.')])), new OA\Response(response: 401, description: 'Authentification requise'), new OA\Response(response: 403, description: 'Rôle non autorisé'), new OA\Response(response: 404, description: 'Événement introuvable')])]
final class EvenementCalendrierDocumentation {}
