<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'PresencePayload', type: 'object', required: ['presences'], properties: [new OA\Property(property: 'presences', type: 'array', minItems: 1, items: new OA\Items(type: 'object', required: ['id_etudiant', 'statut'], properties: [new OA\Property(property: 'id_etudiant', type: 'integer'), new OA\Property(property: 'statut', type: 'string', enum: ['present', 'absent'])]))])]
#[OA\Get(path: '/enseignant/liste-presence', operationId: 'listerSeancesPresence', summary: 'Lister les séances accessibles pour l’appel', tags: ['Liste de présence'], security: [['sanctum' => []]], parameters: [
    new OA\Parameter(name: 'id_matiere', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'id_cours', in: 'query', schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'id_promotion', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'date_debut', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'date_fin', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
], responses: [new OA\Response(response: 200, description: 'Séances de l’enseignant et état de leur feuille.'), new OA\Response(response: 401, description: 'Non authentifié.'), new OA\Response(response: 403, description: 'Rôle enseignant requis.')])]
#[OA\Get(path: '/enseignant/liste-presence/{seance}', operationId: 'afficherListePresence', summary: 'Afficher les étudiants concernés par une séance', description: 'Les étudiants sont calculés côté serveur depuis l’année, le niveau et la promotion de la séance.', tags: ['Liste de présence'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'seance', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Feuille et étudiants concernés.'), new OA\Response(response: 404, description: 'Séance absente ou appartenant à un autre enseignant.')])]
#[OA\Put(path: '/enseignant/liste-presence/{seance}', operationId: 'enregistrerListePresence', summary: 'Enregistrer la liste de présence en brouillon', tags: ['Liste de présence'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'seance', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/PresencePayload')), responses: [new OA\Response(response: 200, description: 'Brouillon enregistré.'), new OA\Response(response: 404, description: 'Séance inaccessible.'), new OA\Response(response: 422, description: 'Liste incomplète, doublon ou étudiant non concerné.')])]
#[OA\Post(path: '/enseignant/liste-presence/{seance}/valider', operationId: 'validerListePresence', summary: 'Valider définitivement la liste de présence', description: 'Opération irréversible. Chaque absent reçoit automatiquement un cours à faire.', tags: ['Liste de présence'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'seance', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: false, content: new OA\JsonContent(ref: '#/components/schemas/PresencePayload')), responses: [new OA\Response(response: 200, description: 'Liste validée définitivement.'), new OA\Response(response: 404, description: 'Séance inaccessible.'), new OA\Response(response: 422, description: 'Séance non réalisée, feuille absente/incomplète ou déjà validée.')])]
final class ListePresenceDocumentation {}
