<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'AnneeAcademiquePayload', type: 'object', required: ['libelle', 'date_debut', 'date_fin'], properties: [new OA\Property(property: 'libelle', type: 'string', example: '2026-2027'), new OA\Property(property: 'date_debut', type: 'string', format: 'date', example: '2026-09-01'), new OA\Property(property: 'date_fin', type: 'string', format: 'date', example: '2027-07-31'), new OA\Property(property: 'active', type: 'boolean', default: false)])]
#[OA\Schema(schema: 'AnneeAcademique', type: 'object', allOf: [new OA\Schema(ref: '#/components/schemas/AnneeAcademiquePayload')], properties: [new OA\Property(property: 'id', type: 'integer', readOnly: true), new OA\Property(property: 'user_id', type: 'integer', nullable: true, readOnly: true), new OA\Property(property: 'created_by', type: 'integer', nullable: true, readOnly: true)])]
#[OA\Schema(schema: 'PromotionPayload', type: 'object', required: ['code', 'num_promotion', 'id_annee_academique', 'id_niveau'], properties: [new OA\Property(property: 'code', type: 'string', example: 'PROMO-2026-A1'), new OA\Property(property: 'num_promotion', type: 'integer', minimum: 1, maximum: 65535, example: 1), new OA\Property(property: 'id_annee_academique', type: 'integer'), new OA\Property(property: 'id_niveau', type: 'integer'), new OA\Property(property: 'statut', type: 'string', default: 'Active'), new OA\Property(property: 'date_ouverture', type: 'string', format: 'date', nullable: true), new OA\Property(property: 'date_cloture', type: 'string', format: 'date', nullable: true)])]
#[OA\Schema(schema: 'Promotion', type: 'object', allOf: [new OA\Schema(ref: '#/components/schemas/PromotionPayload')], properties: [new OA\Property(property: 'id', type: 'integer', readOnly: true), new OA\Property(property: 'nombre_etudiants', type: 'integer', readOnly: true), new OA\Property(property: 'niveau', ref: '#/components/schemas/Niveau'), new OA\Property(property: 'annee_academique', ref: '#/components/schemas/AnneeAcademique')])]
#[OA\Schema(schema: 'MatiereCoursImbriquePayload', type: 'object', required: ['libelle'], properties: [new OA\Property(property: 'code', type: 'string', nullable: true), new OA\Property(property: 'libelle', type: 'string', example: 'La Trinité'), new OA\Property(property: 'volume_horaire', type: 'number', format: 'float', minimum: 0, default: 0), new OA\Property(property: 'coefficient', type: 'number', format: 'float', minimum: 0, default: 1), new OA\Property(property: 'ordre', type: 'integer', minimum: 1), new OA\Property(property: 'actif', type: 'boolean', default: true)])]
#[OA\Schema(schema: 'MatiereModuleImbriquePayload', type: 'object', required: ['libelle', 'cours'], properties: [new OA\Property(property: 'code', type: 'string', nullable: true), new OA\Property(property: 'libelle', type: 'string', example: 'Christologie'), new OA\Property(property: 'ordre', type: 'integer', minimum: 1), new OA\Property(property: 'description', type: 'string', nullable: true), new OA\Property(property: 'cours', type: 'array', minItems: 1, items: new OA\Items(ref: '#/components/schemas/MatiereCoursImbriquePayload'))])]
#[OA\Schema(schema: 'MatierePayload', type: 'object', required: ['code', 'libelle', 'id_niveau'], properties: [new OA\Property(property: 'code', type: 'string', example: 'MAT-BIB-001'), new OA\Property(property: 'libelle', type: 'string', example: 'Introduction biblique'), new OA\Property(property: 'id_niveau', type: 'integer'), new OA\Property(property: 'coefficient', type: 'number', format: 'float', default: 1), new OA\Property(property: 'volume_horaire', type: 'number', format: 'float', minimum: 0, default: 0, example: 30), new OA\Property(property: 'type', type: 'string', nullable: true), new OA\Property(property: 'description', type: 'string', nullable: true), new OA\Property(property: 'objectifs', type: 'string', nullable: true), new OA\Property(property: 'prerequis', type: 'string', nullable: true), new OA\Property(property: 'note_validation', type: 'number', format: 'float', default: 10), new OA\Property(property: 'obligatoire', type: 'boolean', default: true), new OA\Property(property: 'active', type: 'boolean', default: true), new OA\Property(property: 'version', type: 'integer', default: 1), new OA\Property(property: 'modules', type: 'array', minItems: 1, items: new OA\Items(ref: '#/components/schemas/MatiereModuleImbriquePayload'))])]
#[OA\Schema(schema: 'Matiere', type: 'object', allOf: [new OA\Schema(ref: '#/components/schemas/MatierePayload')], properties: [new OA\Property(property: 'id', type: 'integer', readOnly: true), new OA\Property(property: 'niveau', ref: '#/components/schemas/Niveau')])]
#[OA\Schema(schema: 'ModulePayload', type: 'object', required: ['id_matiere', 'libelle'], properties: [new OA\Property(property: 'id_matiere', type: 'integer'), new OA\Property(property: 'code', type: 'string', nullable: true), new OA\Property(property: 'libelle', type: 'string'), new OA\Property(property: 'ordre', type: 'integer', default: 1), new OA\Property(property: 'description', type: 'string', nullable: true)])]
#[OA\Schema(schema: 'Module', type: 'object', allOf: [new OA\Schema(ref: '#/components/schemas/ModulePayload')], properties: [new OA\Property(property: 'id', type: 'integer', readOnly: true), new OA\Property(property: 'nombre_cours', type: 'integer', readOnly: true), new OA\Property(property: 'matiere', ref: '#/components/schemas/Matiere')])]
#[OA\Schema(schema: 'CoursPayload', type: 'object', required: ['id_module', 'libelle'], properties: [new OA\Property(property: 'id_module', type: 'integer'), new OA\Property(property: 'code', type: 'string', nullable: true), new OA\Property(property: 'libelle', type: 'string'), new OA\Property(property: 'volume_horaire', type: 'number', format: 'float', default: 0), new OA\Property(property: 'coefficient', type: 'number', format: 'float', default: 1), new OA\Property(property: 'ordre', type: 'integer', default: 1), new OA\Property(property: 'actif', type: 'boolean', default: true)])]
#[OA\Schema(schema: 'Cours', type: 'object', allOf: [new OA\Schema(ref: '#/components/schemas/CoursPayload')], properties: [new OA\Property(property: 'id', type: 'integer', readOnly: true), new OA\Property(property: 'module', ref: '#/components/schemas/Module')])]
#[OA\Schema(schema: 'PreInscriptionPayload', type: 'object', required: ['nom', 'prenoms', 'civilite_id', 'email', 'telephone', 'eglise_id', 'photo_identite'], properties: [new OA\Property(property: 'nom', type: 'string'), new OA\Property(property: 'prenoms', type: 'string'), new OA\Property(property: 'civilite_id', type: 'integer', description: 'Identifiant d’une civilité existante', example: 1), new OA\Property(property: 'date_naissance', type: 'string', format: 'date', nullable: true), new OA\Property(property: 'nationalite', type: 'string', nullable: true), new OA\Property(property: 'email', type: 'string', format: 'email'), new OA\Property(property: 'telephone', type: 'string'), new OA\Property(property: 'adresse', type: 'string', nullable: true), new OA\Property(property: 'eglise_id', type: 'integer', description: 'Identifiant d’une église existante et non supprimée', example: 1), new OA\Property(property: 'photo_identite', type: 'string', format: 'binary', description: 'Photo d’identité (jpg, jpeg, png ou webp, 2 Mo maximum)'), new OA\Property(property: 'pieces_requises', type: 'array', nullable: true, items: new OA\Items(type: 'string')), new OA\Property(property: 'observations', type: 'string', nullable: true)])]
#[OA\Schema(schema: 'PreInscriptionResultat', type: 'object', properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'matricule', type: 'string', example: 'EBAC-0001-2026'), new OA\Property(property: 'numero_dossier', type: 'string', example: 'ZRM0002026'), new OA\Property(property: 'statut', type: 'string', example: 'Préinscrit'), new OA\Property(property: 'statut_dossier', type: 'string', example: 'Incomplet')])]
final class ParametreDocumentation {}
