<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Rôles', description: 'Gestion des rôles, droits et autorisations. Permission ROLE_GERER requise.')]
#[OA\Get(path: '/administration/roles', tags: ['Rôles'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Liste paginée des rôles'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Post(path: '/administration/roles', tags: ['Rôles'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Rôle créé'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Get(path: '/administration/roles/catalogue-droits', tags: ['Rôles'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Catalogue des droits par rôle'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Get(path: '/administration/roles/matrice-autorisations', tags: ['Rôles'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Matrice complète des autorisations'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Get(path: '/administration/roles/{role}', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Détail du rôle'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 404, description: 'Rôle introuvable')])]
#[OA\Put(path: '/administration/roles/{role}', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Rôle modifié'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Patch(path: '/administration/roles/{role}', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Rôle modifié'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Delete(path: '/administration/roles/{role}', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Rôle supprimé'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 404, description: 'Rôle introuvable'), new OA\Response(response: 422, description: 'Rôle protégé ou encore utilisé')])]
#[OA\Get(path: '/administration/roles/{role}/droits', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Droits du rôle'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Patch(path: '/administration/roles/{role}/droits/{permission}', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer')), new OA\PathParameter(name: 'permission', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['accordee'], properties: [new OA\Property(property: 'accordee', type: 'boolean')])), responses: [new OA\Response(response: 200, description: 'Droit modifié'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Get(path: '/administration/roles/{role}/matrice-autorisations', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Matrice des autorisations du rôle'), new OA\Response(response: 403, description: 'Accès refusé')])]
#[OA\Put(path: '/administration/roles/{role}/autorisations', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['autorisations'], properties: [new OA\Property(property: 'autorisations', type: 'array', items: new OA\Items(type: 'object'))])), responses: [new OA\Response(response: 200, description: 'Autorisations synchronisées'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
#[OA\Put(path: '/administration/roles/{role}/permissions', tags: ['Rôles'], security: [['sanctum' => []]], parameters: [new OA\PathParameter(name: 'role', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['permission_ids'], properties: [new OA\Property(property: 'permission_ids', type: 'array', items: new OA\Items(type: 'integer'))])), responses: [new OA\Response(response: 200, description: 'Permissions synchronisées'), new OA\Response(response: 403, description: 'Accès refusé'), new OA\Response(response: 422, description: 'Données invalides')])]
final class RoleDocumentation
{
}
